// <auto-generated />
namespace E_Store.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class A1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(A1));
        
        string IMigrationMetadata.Id
        {
            get { return "201702191306491_A1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
